server:
  port: 8080

# database HikariCP相关配置
spring:
  datasource:
    url: jdbc:mysql://xxxx/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: xxxx

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: xxxx
    port: 6379
    password:
    timeout: 30000
    lettuce:
      pool:
        max-active: 16   # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 4     # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接
        max-wait: 10000    # 连接池最大阻塞等待时间（使用负值表示没有限制）

## 日志配置
logging:
  # 日志级别
  logLevel: INFO
  # 日志保留天数，默认10天
  maxHistory: 5


## ------------------------------业务相关配置写到下面-------------------------
gamefi:
  common:
    url: https://main-seed.starcoin.org
    chain-id: 1
  aww:
    common:
      contract-address: "0x16a8bf4d0c3718518d81f132801e4aaa"
    websocket:
      websocket-host: 10.13.22.40
      websocket-port: 9870
    content:
      aww-module: "AWW"
      arm-module: "ARM"
      aww-game-module: "AWWGame"
      market-module: "ARMMarket"
      scripts-module: "AWWScripts"
      nft-name: "aww arm"
      title-page-image: "https://test.kikoswap.com/v1/nft/image/group/1"
      description: "aww arms"
      image-info-api: "https://test.kikoswap.com/v1/nft/image/info/"



